"use client";

import React, { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import api from "../lib/api";

interface AIExplanationModalProps {
  bookId: string | null;
  bookTitle: string;
  onClose: () => void;
}

export const AIExplanationModal: React.FC<AIExplanationModalProps> = ({
  bookId,
  bookTitle,
  onClose
}) => {
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    setIsHydrated(true);
  }, []);

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["explanation", bookId],
    queryFn: async () => {
      if (!bookId) throw new Error("Book ID is required");
      console.log(`[AIExplanation] Fetching explanation for book: ${bookId}`);
      try {
        const response = await api.get(`/api/recommendations/${bookId}/explain`);
        console.log(`[AIExplanation] Success:`, response.data);
        return response.data;
      } catch (err) {
        console.error("[AIExplanation] Failed to fetch explanation:", err);
        throw err;
      }
    },
    enabled: isHydrated && !!bookId,
    staleTime: 1000 * 60 * 60,
    retry: 2,
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
  });

  if (!bookId) return null;

  const handleClose = () => {
    console.log("[AIExplanation] Modal closed");
    onClose();
  };

  return (
    <div 
      className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
      onClick={handleClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="ai-modal-title"
    >
      <div 
        className="bg-white rounded-2xl p-6 max-w-2xl w-full mx-auto max-h-[80vh] overflow-y-auto shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-start mb-4">
          <div>
            <h2 id="ai-modal-title" className="font-bold text-xl text-gray-900">✨ Why this book?</h2>
            <p className="text-sm text-gray-400 line-clamp-2 mt-1">for {bookTitle}</p>
          </div>
          <button 
            onClick={handleClose}
            className="text-gray-400 hover:text-gray-600 transition-colors text-2xl font-bold leading-none"
            aria-label="Close modal"
          >
            ×
          </button>
        </div>

        <div className="min-h-[100px] my-6">
          {isLoading ? (
            <div className="space-y-3">
              <div className="animate-pulse space-y-2">
                <div className="h-4 bg-gray-200 rounded w-3/4"></div>
                <div className="h-4 bg-gray-200 rounded w-full"></div>
                <div className="h-4 bg-gray-200 rounded w-5/6"></div>
                <div className="h-4 bg-gray-200 rounded w-4/5"></div>
              </div>
              <p className="text-xs text-gray-400 mt-4 animate-pulse">🤖 AI is analyzing your reading preferences...</p>
            </div>
          ) : isError ? (
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
              <p className="text-gray-700 text-sm leading-relaxed font-medium mb-2">
                📚 Couldn't generate AI explanation
              </p>
              <p className="text-gray-600 text-sm">
                But this book is recommended based on your reading preferences and ratings.
              </p>
              {error && (
                <p className="text-xs text-gray-500 mt-3 pt-3 border-t border-amber-200">
                  {error instanceof Error ? error.message : "Unknown error occurred"}
                </p>
              )}
            </div>
          ) : data?.explanation ? (
            <div>
              <p className="text-gray-800 text-base leading-relaxed mb-4 font-medium">
                {data.explanation}
              </p>
              
              <div className="mt-4 flex items-center gap-2 flex-wrap">
                {data.isAIGenerated ? (
                  <span className="text-xs text-purple-600 flex items-center gap-1 bg-purple-50 px-3 py-1.5 rounded-full border border-purple-200">
                    ✨ Generated by Gemini AI
                  </span>
                ) : (
                  <span className="text-xs text-blue-600 flex items-center gap-1 bg-blue-50 px-3 py-1.5 rounded-full border border-blue-200">
                    📊 Based on your reading patterns
                  </span>
                )}
              </div>
            </div>
          ) : (
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-center">
              <p className="text-gray-600 text-sm">No explanation available</p>
            </div>
          )}
        </div>

        <div className="flex gap-3 mt-6 pt-4 border-t border-gray-200">
          <button
            onClick={handleClose}
            className="flex-1 px-4 py-2.5 text-gray-700 font-medium border border-gray-300 rounded-xl hover:bg-gray-50 transition-colors"
          >
            Close
          </button>
          <a
            href={`/book/${bookId}`}
            className="flex-1 bg-blue-600 text-white font-medium py-2.5 rounded-xl hover:bg-blue-700 transition-colors text-center"
          >
            View Book →
          </a>
        </div>
      </div>
    </div>
  );
};
